### ISSUE TITLE
[error] 2572#0: *13748 FastCGI sent in stderr: "PHP message: Didn't get slug

### ISSUE THREAD

**Issue by KashCorp** [aaronpk/OwnYourGram#10]
Hello,

I'm new in the indieweb, I set a Known instance at this address https://kash.space
Then I install the IndiePub plugin and connect my Instagram account to bridgy. Finally I create my account on OwnYourGram. I did the test who was a succes but nothing has been post on my known. 

There is the tail of the error log of nginx. To be honest I'm not sure to understand.

Thank you.

`2015/06/23 14:53:21 [warn] 2572#0: *13748 a client request body is buffered to a temporary file /etc/nginx/client_body_temp/0000000142, client: 173.230.155.197, server: kash.space, request: "POST /micropub/endpoint HTTP/1.1", host: "kash.space"
2015/06/23 14:53:24 [error] 2572#0: *13748 FastCGI sent in stderr: "PHP message: Didn't get slug
PHP message: Setting resilient slug
PHP message: Set resilient slug
PHP message: Didn't get slug
PHP message: Setting resilient slug
PHP message: Set resilient slug
PHP message: Known (kash.space): INFO - Pinging https://withknown.superfeedr.com/ with data hub.mode=publish&hub.url=https%3A%2F%2Fkash.space%2F,https%3A%2F%2Fkash.space%2F%3F_t%3Drss,https%3A%2F%2Fkash.space%2Fcontent%2Fphotos%2F,https%3A%2F%2Fkash.space%2Fcontent%2Fphotos%2F%3F_t%3Drss,https%3A%2F%2Fkash.space%2Fcontent%2Fall%2F,https%3A%2F%2Fkash.space%2Fcontent%2Fall%2F%3F_t%3Drss,https%3A%2F%2Fkash.space%2Ftag%2F%23ecology,https%3A%2F%2Fkash.space%2Ftag%2F%3F_t%3Drss,https%3A%2F%2Fkash.space%2Ftag%2F%23nature,https%3A%2F%2Fkash.space%2Ftag%2F%3F_t%3Drss,https%3A%2F%2Fkash.space%2Ftag%2F%23bee,https%3A%2F%2Fkash.space%2Ftag%2F%3F_t%3Drss 5" while reading response header from upstream, client: 173.230.155.197, server: kash.space, request: "POST /micropub/endpoint HTTP/1.1", upstream: "fastcgi://unix:/var/www/kash.space/php.sock:", host: "kash.space"
2015/06/23 14:54:16 [warn] 2572#0: *13754 an upstream response is buffered to a temporary file /etc/nginx/fastcgi_temp/3/14/0000000143 while reading upstream, client: 109.128.250.169, server: kash.space, request: "GET /file/dec3880545c2f81966792658ac433569 HTTP/1.1", upstream: "fastcgi://unix:/var/www/kash.space/php.sock:", host: "kash.space", referrer: "https://kash.space/"
2015/06/23 14:54:16 [warn] 2572#0: *13768 an upstream response is buffered to a temporary file /etc/nginx/fastcgi_temp/4/14/0000000144 while reading upstream, client: 109.128.250.169, server: kash.space, request: "GET /file/4441267f722b75f221201bf6b4dc8fbb HTTP/1.1", upstream: "fastcgi://unix:/var/www/kash.space/php.sock:", host: "kash.space", referrer: "https://kash.space/"`

**Comment by aaronpk** [comment]
I think this is a question for Known, try posting there?

**Comment by aaronpk** [comment]
I'm going to close this. Feel free to re-open or open a new issue if you're still having problems!
