### ISSUE TITLE
post-by-mail email subject not sent as "name" property

### ISSUE THREAD

**Issue by diplix** [aaronpk/OwnYourGram#14]
this is the $_POST variable that the micropub endpoint receives:
```
Array
(
[h] => entry
[access_token] => xxx
[content] => test — ignore
[published] => 2015-07-25T07:36:05+00:00
[syndication] => so sah ich meine mutter mit 8 jahren
)
```

looks like the email subject gets sent as the syndication property instead of the name property.

**Comment by aaronpk** [comment]
Thanks. That was a silly mistake because I was tired. Fixed in debb72aef354e785ef08ec67dcf74fa47e5bb650
