### ISSUE TITLE
considering non square and higher resolution images for ownyourgram

### ISSUE THREAD

**Issue by diplix** [aaronpk/OwnYourGram#15]
i’d vote for ownyourgram accepting non square images, it’s an option that you can activate in the instagram client configuration just a click away: http://stackoverflow.com/questions/32393998/instagram-api-return-not-square-photos-with-white-lines/32404380#32404380

cons: 
* micropub clients expecting square images
* the new top-user overview, but that could use the thumnail image, that the API still return in square ratio:

```
[images] => stdClass Object
(
[low_resolution] => stdClass Object
(
[url] => https://scontent.cdninstagram.com/hphotos-xaf1/t51.2885-15/e35/p320x320/11376346_469642079882392_675297296_n.jpg
[width] => 320
[height] => 400
)
[thumbnail] => stdClass Object
(
[url] => https://scontent.cdninstagram.com/hphotos-xaf1/t51.2885-15/s150x150/e35/c0.135.1080.1080/11376346_469642079882392_675297296_n.jpg
[width] => 150
[height] => 150
)
[standard_resolution] => stdClass Object
(
[url] => https://scontent.cdninstagram.com/hphotos-xaf1/t51.2885-15/sh0.08/e35/p640x640/11376346_469642079882392_675297296_n.jpg
[width] => 640
[height] => 800
)
)
```

also, there’s an undocumented image format of 1080 x 1080 instead of only 640 x 640: http://stackoverflow.com/questions/14016142/instagram-api-custom-image-width/32070650#32070650

i think it would be nice to get a higher resolution image to my micropub endpoint, where i can still scal it down, if needed.

**Comment by aaronpk** [comment]
Nothing about OwnYourGram requires or expects square images, so I went ahead and turned on that option for the Instagram client. I'd be a little concerned about trying to use the undocumented 1080 image, so I'll pass on that for now. In the mean time, enjoy non-square images!

**Comment by diplix** [comment]
thanks!
