### ISSUE TITLE
ownyourgram won’t send gram to my micropub endpoint …

### ISSUE THREAD

**Issue by diplix** [aaronpk/OwnYourGram#16]
… unless i press the test button.
ownyour gram show an old response from my micropub endpoint and only after i press test, the gram will be posted to my site. i didn’t check the logs on my side, but may actually nothing changed on my side? maybe i have to renew my instagram permissions?

![bildschirmfoto 2015-09-19 um 00 50 19](https://cloud.githubusercontent.com/assets/4541494/9972756/9cc1caa6-5e68-11e5-9785-a3af1f320384.png)
(before i press test)

![bildschirmfoto 2015-09-19 um 00 55 28](https://cloud.githubusercontent.com/assets/4541494/9972790/101e3ff2-5e69-11e5-8f26-f4fb4278b396.png)
(after i press "test")

**Comment by adactio** [comment]
I'm seeing the same issue, I think. About 48 hours ago, OwnYourGram stopped posting automatically when I posted something on Instagram. But if I log in to OwnYourGram and do a test post, everything works fine.

**Comment by aaronpk** [comment]
The same thing happened to one of my accounts as well. Logging in and doing a test post worked, but I haven't been getting new photos from it yet. Unfortunately I don't have a lot of visibility into this kind of thing from my end. 

The Instagram API is supposed to deliver photos to my app for anyone who has logged in with it. (see https://instagram.com/developer/realtime/) Right now I can see that the app's subscription is active, and there are still *some* photos coming through. I'm just not getting post requests from Instagram for some users.

**Comment by adactio** [comment]
Hmmm ...I thought this issue had cleared itself up, but now it's back again: any time I post to Instagram, it doesn't show up on my site unless I go to ownyourgram.com and do a manual refresh.

**Comment by diplix** [comment]
FYI, i disconnected instagram and ownyourgram (a week ago), re-authenticated, but it didn’t fix the issue.

**Comment by aaronpk** [comment]
Same for me, it's still not sending my photos over. If this were broken for everyone I would suspect it's something wrong with OwnYourGram, but it's still working for a lot of people. Basically Instagram is just not including some people's posts when they send updates to the app. I think I'm going to try making a brand new client ID, but that is going to require everyone to log in to OwnYourGram again. I'll post back when I decide what to do.

**Comment by aaronpk** [comment]
oookay well I managed to track down one issue, which caused the upload worker to crash a day-ish ago, stopping everyone's photos from uploading. I apologize for any duplicates that ended up on your sites, I know that there are a few extra photos on @adactio's site now. So that at least explains why the photos stopped the other day.

I'm pretty sure the underlying issue is still present, that some people are just missing from the realtime feed. Will keep digging.

**Comment by aaronpk** [comment]
Didn't realized it has been so long since last posting here. Still no luck tracking down why Instagram is only sending realtime pings for some users. I'm considering adding a polling mechanism to catch the cases when Instagram forgets to ping OwnYourGram.

**Comment by diplix** [comment]
that would be great — and it would also lead to more „Top users this week“ — which are actually the lucky one, that still get pings from instagram.

**Comment by kylewm** [comment]
I wonder if you hit an undocumented user limit for the realtime API. I know [at about ~50 users](https://github.com/snarfed/bridgy/issues/57#issuecomment-35161989) the Twitter streaming API starts throwing a fit

**Comment by kylewm** [comment]
Also note that the /developers/realtime link is broken and now https://instagram.com/developer/deprecated/realtime/ though https://instagram.com/developer/subscriptions/ seems to describe the same feature.

**Comment by aaronpk** [comment]
@kylewm that's interesting. Strangely, the endpoint documented on the new page for listing subscriptions does in fact show my subscription is active! 

```json
{
  "meta": {
    "code": 200
  },
  "data": [
    {
      "object": "user",
      "object_id": null,
      "aspect": "media",
      "callback_url": "http://ownyourgram.com/instagram/callback",
      "type": "subscription",
      "id": "4308036"
    }
  ]
}
```

**Comment by aaronpk** [comment]
I'm going to close this issue since the realtime capability will be shut off next week anyway, and I have to switch to polling. See #25 and #26.
