### ISSUE TITLE
Send location as h-card

### ISSUE THREAD

**Issue by kylewm** [aaronpk/OwnYourGram#19]
Note: place_name is not currently in the list of parameters for an h-entry https://indiewebcamp.com/Micropub#h-entry ... perhaps it is an OYG specific extension?

**Comment by aaronpk** [comment]
It's definitely something specific to OYG, but I would love to change it. I'm thinking maybe a nested h-card, or just simply place-name like you suggest.

**Comment by kylewm** [comment]
FWIW, in silo.pub I'm only using it for a suggestion to the Facebook search API. So far the other services that accept location don't have venues, just lat/long

**Comment by aaronpk** [comment]
I want to change this to "p-location h-card" which will end up being a nested h-card in the "location" property.

**Comment by kylewm** [comment]
> FWIW, in silo.pub I'm only using it for a suggestion to the Facebook search API.

(I turned this off very quickly after the first time I used it, it was super inaccurate)

**Comment by aaronpk** [comment]
Facebook venues are terribad

**Comment by aaronpk** [comment]
Done in 4bbb96abe388b41492449953ebca7750d1421f2b, behind a feature flag you can enable on the dashboard!
