### ISSUE TITLE
Syndication link not being passed through

### ISSUE THREAD

**Issue by davidmead** [aaronpk/OwnYourGram#20]
I'm noticing that the syndication link isn't being passed to my Wordpress post when a gram is posted.

Thought it was an issue with Brid.gy at first, but then found no links back to Instagram from my post via OwnYourGram.

What I get, content wise, is...

```
<div class="e-content">
Beats to UX too
</div>

[gallery size=full columns=1]
```
Any ideas?

**Comment by aaronpk** [comment]
Unless something has changed between last night and today, this should be working fine. The parameter it sends is called `syndication`. You can use the "test" button to have it send a post request to your site so you can check.

**Comment by davidmead** [comment]
I can do a successful test from OwnYourGram @aaronpk. And it posts the photo, but I don't get the `syndication` URL passed to my page in Wordpress.

The test post is at http://davidjohnmead.com/blog/2015/12/08/1510/.  It looks like the categories are coming into the `article` as classes...
```
<article id="post-1510" class="post-1510 post type-post status-publish format-standard hentry category-uncategorized tag-np tag-android tag-aviate tag-music tag-screenshot kind-note">
```
I only noticed it recently, so it looks like no posts going into my WP from Instagram have had this link posted.

Could it be a conflict with an Indieweb plugin?

**Comment by aaronpk** [comment]
It sounds more like the wordpress plugin isn't recognizing the syndication parameter.

**Comment by davidmead** [comment]
That's what I was worried about. I only have the Indieweb pack plugins installed. I'll have to go through and disable them, see which one is causing a conflict with the latest version of WP.

Thanks @aaronpk .

**Comment by florianjacob** [comment]
issue for the wordpress micropub plugin: https://github.com/snarfed/wordpress-micropub/issues/21
