### ISSUE TITLE
erro 4040 by clicking on profile 

### ISSUE THREAD

**Issue by danito** [aaronpk/OwnYourGram#24]
Hi,
when I click on the link to my profile it gives me a 404.

> http://ownyourgram.com/user?domain=https%3A%2F%2Fnxd4n.nixekinder.be%2Fprofile%2Fnxd4n

**Comment by skddc** [comment]
Same for me.

Also, on the "Instagram" page, it shows me the last picture and I sent the "test" request for two, but afterwards it won't post pictures automatically, even though it says that it will once the test is successful.

Profile link is https://ownyourgram.com/user?domain=https%3A%2F%2Fupdates.kip.pe%2Fprofile%2Fbasti (I signed in with https://updates.kip.pe).

**Comment by aaronpk** [comment]
This is the same as #16

**Comment by danito** [comment]
Hi,
My issue is about the error 404 when clicking on the link in the upper right corner. I don't think it has to do with IG's api change, does it?

**Comment by aaronpk** [comment]
Sorry, you're right. That link actually shouldn't even be there, there isn't a profile page. I will get rid of it, but it's not hurting anything in the mean time.

**Comment by danito** [comment]
maybe not as link, but seeing that you're still logged in as [profile] might be interesting (if you use more than one profile/hosts).
