### ISSUE TITLE
Issue un-authenticating while moving from one site to another

### ISSUE THREAD

**Issue by chrisaldrich** [aaronpk/OwnYourGram#29]
I was moving my Instagram posting target from a WordPress install to a Known install.

For my WP install, on IG I revoked access from OYG and then reauthenticated for my Known site at http://stream.boffosocko.com. However, I'm still getting micropub posts to the WP install at www.boffosocko.com. (Note that I would like to keep both sites listed in my Instagram profile/bio, if that makes a difference.)

Is there something else I need to do to deactivate ownyourgram from publishing to my WordPress install?

Is it possible that OwnYourGram holds the same authentication for two separate sites using the same Instagram account? This could mean that one would need an "off" switch through the ownyourgram interface to deauthorize one site. It could also separately be the case that Instagram didn't flush a cache which allowed my last IG post to the WP site to slip through.

**Comment by aaronpk** [comment]
All you should need to do is log in on ownyourgram.com with the new site. It allows an instagram username to be associated with only one website, and always uses the latest one. Sorry I didn't notice this before!

**Comment by aaronpk** [comment]
Sorry about this again. I realized that with the change away from the Instagram API, this behavior did actually change. I just added a "disconnect" button in the interface, so you can force your OYG account to be disconnected from Instagram. Also I fixed it so when you connect an IG account to a new OYG account, it properly disconnects the old OYG account. To fix this on your end, you will probably have to log in as `www.boffosocko.com` and click the new "disconnect" button.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/aaronpk/OwnYourGram/issues/29#issuecomment-267796312" class="u-in-reply-to"></a>I've tried a couple of times (when you posted it and twice since) to actually log in and do this, but when I input my site for IndieAuth, the following URL loads with a white page and doesn't actually allow me to log into the UI. https://ownyourgram.com/auth/start?me=http%3A%2F%2Fboffosocko.com&redirect_uri=https%3A%2F%2Fownyourgram.com%2Findieauth

I suspected it might be a temporary problem, but perhaps not? Is something preventing me from logging in to turn it off? I'm not having any issues logging in via IndieAuth on other sites presently, just OYG.

**Comment by aaronpk** [comment]
Just wanted to check if this is still happening!

**Comment by aaronpk** [comment]
Going to close this since there hasn't been any activity. Feel free to open a new issue if there's still a problem.
