### ISSUE TITLE
Error when using 'post' button

### ISSUE THREAD

**Issue by davidmead** [aaronpk/OwnYourGram#32]
I had three Instagram posts that did not appear on my blog. First one posted fine when using the new 'post' button.

![image](https://cloud.githubusercontent.com/assets/1266930/21531161/e57f2412-cd13-11e6-8bbe-7196412a092b.png)

The other two threw errors.

![image](https://cloud.githubusercontent.com/assets/1266930/21531136/c5c591d8-cd13-11e6-8dd5-b38a3a5ea378.png)

![image](https://cloud.githubusercontent.com/assets/1266930/21531142/d2859c10-cd13-11e6-9d5b-ad535f062785.png)

**Comment by aaronpk** [comment]
It is likely that your site isn't recognizing some part of these specific photos. Has this continued to be a problem?
