### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by calumryan** [aaronpk/OwnYourGram#33]
Testing my PHP endpoint - do all 10 parameters expect to be handled even if empty?

**Comment by aaronpk** [comment]
Your endpoint should handle the parameters it knows about, and ignore (or save and ignore) the ones it doesn't know about. There's a sentence in the Micropub spec about this, I'll look for a link

**Comment by aaronpk** [comment]
https://www.w3.org/TR/micropub/#unrecognized-properties
