### ISSUE TITLE
Support Instagram's new multi-photo posts

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/OwnYourGram#34]
Instagram now supports multiple photos and videos per post. https://www.instagram.com/p/BQ0mDB2gV_O/

https://indieweb.org/multi-photo

**Comment by aaronpk** [comment]
Upon reviewing Instagram's implementation of multi-photos, they actually appear closer to my implementation of albums in p3k. Each photo has its own permalink, and can collect their own comments.

**Comment by aaronpk** [comment]
I just reviewed Instagram's implementation again and I think I have a path forward now.

There is still only one caption associated with the collection of photos, and I can't find a way to comment or like an individual photo using the mobile app, so they act as a single post.

My own site supports native multi-photo posts where a single post can have multiple images, and I have a few examples of that already.

Since Micro.blog doesn't support multiple photos itself, I have a few options for how to create a fallback mode so that they'll appear properly on Micro.blog and other sites that don't natively support multi photos.

* Post each image in the Instagram multi photo as it's own separate photo post. This is the least analogous method compared to Instagram's implementation, as each photo would have its own URL and be able to be liked and commented on individually.
* Send the Instagram post to Micro.blog as an article with embedded img tags, so that they would appear as a single post in Micro.blog. The downside is Micro.blog would be hotlinking to the instagram img URLs rather than copying the images.

Amy thoughts on which format you'd prefer for your own site? I could also make this another setting to give people a few options.

**Comment by manton** [comment]
Considering this some more, I think referencing Instagram URLs for the img tags isn't what people will want. It's better if the photos are copied. (Also, Micro.blog is going to be updated to escape more HTML in the future, so including img tags should be discouraged.)

Currently that would only leave the option of separate posts. Ideally Micro.blog would be updated to support multiple photos in a single post too.

**Comment by manton** [comment]
Basic support for uploading multiple photos is now on Micro.blog. Still testing, but I think this will be the best solution.

**Comment by aaronpk** [comment]
This is live! Here's some more information about how it works: https://aaronparecki.com/2017/09/23/8/ownyourgram-multi-photo
