### ISSUE TITLE
Clicking the "Upgrade Me" button doesn't change anything

### ISSUE THREAD

**Issue by Kongaloosh** [aaronpk/OwnYourGram#43]
Clicking the button under:
> Upcoming change! The Micropub spec now requires values be sent as arrays instead of as comma-separated lists. When you are ready to receive the category property as an array, click the button below to switch.

Doesn't change anything.

**Comment by aaronpk** [comment]
I'm curious, was your instagram account already connected at the time? I think I fixed it regardless. Feel free to reopen if it's still broken. Thanks!
