### ISSUE TITLE
support syndicating to other silos

### ISSUE THREAD

**Issue by snarfed** [aaronpk/OwnYourGram#44]
today at IWS, @scottjenson mentioned that it'd be nice if OwnYourGram could syndicate to other silos in the micropub request, if/when the server has any. @dshanske agreed. any interest in adding that?

i know it's probably non-trivial, and would take some extra UI. just a thought!

**Comment by aaronpk** [comment]
It actually supports this already! On the dashboard, there's an "Automatic Syndication" section. If you have syndication endpoints that it can find, you'll see a menu where you can define syndication rules. You can even choose whether to syndicate to specific places based on keywords in the post!

**Comment by snarfed** [comment]
oh wow, awesome! cc @scottjenson. i didn't see that in the docs, but maybe i missed it. cool!
