### ISSUE TITLE
Only getting one category on posts with multiple hashtags

### ISSUE THREAD

**Issue by Kongaloosh** [aaronpk/OwnYourGram#49]
For instance,  [the post here](https://www.instagram.com/p/BZclJW0H4cZ/) I only receive the category: `food`.

**Comment by aaronpk** [comment]
hm, from what I can tell, it should be sending both categories just fine. I tested the method that builds up the request on your photo and it seemed to work. 

Can you share the actual post request that's being sent? (You can get ownyourgram to post the photo again manually from the website)

**Comment by aaronpk** [comment]
It's possible your site isn't recognizing the array syntax that OwnYourGram sends. It's sending `category[]=foo&category[]=bar` which is recognized by some server-side frameworks (e.g. PHP handles this by default), but if you're doing something out of the ordinary on the server then that might be the issue.

**Comment by aaronpk** [comment]
I'm going to close this since I haven't heard anything in a while. Feel free to chime in if it's still a problem.
