### ISSUE TITLE
RSS feed PubDate is Jan 01 1970 for items posted to WordPress

### ISSUE THREAD

**Issue by jackbaty** [aaronpk/OwnYourGram#50]
I'm unsure if this is specifically an OwnYourGram issue but posts from OwnYourGram to my WordPress blog end up with an invalid date in the RSS feed. No other "normal" posts have the problem, and the WordPress UI indicates the correct date so I'm not clear where the bad date is coming from.

Feed is here: https://snippets.baty.net/feed/

`<link>https://snippets.baty.net/2017/816/</link>
		<comments>https://snippets.baty.net/2017/816/#respond</comments>
		<pubDate>Thu, 01 Jan 1970 00:00:00 +0000</pubDate>`

**Comment by aaronpk** [comment]
@dshanske do you know if this is related to the recent changes to the wordpress micropub plugin?

**Comment by dshanske** [comment]
Yes. The recent changes I made were related to this issue, but it was only pushed to stable, it wasn't pushed to wordpress.org.

**Comment by jackbaty** [comment]
Ah, so it's the plugin rather than specific to OwnYourGram. Thanks. Let me know if I should create an issue on the micropub project instead.

**Comment by dshanske** [comment]
@jackbaty Download the development version and see if it fixes the issue for you. If not, open a new issue.

**Comment by jackbaty** [comment]
Running the latest master of micropub seems to solve the issue with the date. Thanks!
