### ISSUE TITLE
OYG doesn't see my photos

### ISSUE THREAD

**Issue by lostfocus** [aaronpk/OwnYourGram#51]
Since yesterday night the "Import Photos" page shows the warning "We didn't find any photos in your Instagram profile" - and I'm wondering if it might be a unicode issue since the last picture has '🤓' as caption.

**Comment by adactio** [comment]
I’m seeing the same issue for my account.

**Comment by aaronpk** [comment]
uhoh, that might mean the background worker has stopped...

**Comment by aaronpk** [comment]
Confirmed... looks like Instagram's secret `https://www.instagram.com/aaronpk/media/` URL that use to return JSON isn't working anymore. I'll work on a fix.

**Comment by aaronpk** [comment]
Fixed in 58553387cefdf44786769c44d73d47ced853852a

You should see your photos again!

**Comment by lostfocus** [comment]
Yeah, that fixed it. But now I got a `Could not insert post into the database` error, when trying to auto-post that picture.

**Comment by aaronpk** [comment]
Going to close this issue. @lostfocus can you open a new issue with the details of which post is failing if this is still a problem?

**Comment by lostfocus** [comment]
I just tried again, it worked this time. ¯\_(ツ)_/¯ [It was this one.](https://www.instagram.com/p/BbM-jz0nWoJ/)
