### ISSUE TITLE
Can't verify instagram account - says my link is not on my profile page

### ISSUE THREAD

**Issue by voss** [aaronpk/OwnYourGram#52]
I was trying to connect ownyourgram with my instagram account, but I keep getting told that it can't find the link to my website, from my profile page.

![ownyourgram fails to find the URL on my instagram profile page](https://user-images.githubusercontent.com/10601/33635595-769a66fa-da10-11e7-8a1e-bee88fd26203.png)

I've tried in the 'website' field and the 'bio' field. I was wondering if this could have something to do with instagram using what looks to be their own URL redirecter so the anchor element on the page looks like this:

<a class="_ng0lj" href="https://l.instagram.com/?u=https%3A%2F%2Fblog.voss.co%2F&amp;e=ATNbsTSVJhkiwZYfW6Kn4ujouN6Nqg8uAxLCLXKLbyIAYc3wmQ3EqoBcxB5McyraUv7pxCwsjEhA1OU" rel="nofollow me noopener noreferrer" target="_blank">blog.voss.co</a>

When trying in the 'bio' field on the page, my address does show up, but ownyourgram still doesn't like it.

![inside "bio" doesn't seem to cut it either](https://user-images.githubusercontent.com/10601/33635826-77a3fa4c-da11-11e7-99f4-01abe39405dd.png)

If I remove the URL from the bio, then the only place on the page I see my actual URL, protocol and all, is in what looks to be the JSON object called window._sharedData.

Is ownyourgram able to parse the JSON on the page for the URL back to my page?

**Comment by aaronpk** [comment]
That's really strange, I can't tell why this wouldn't be working. OwnYourGram actually makes a request to this undocumented JSON version of your profile URL:

`https://www.instagram.com/l3traset/?__a=1`

I see your address in there just fine:

`"external_url": "https://blog.voss.co/"`

I just did some debugging and it looks like it's working fine now. Did you change anything between filing this issue and about 5 minutes ago?

**Comment by aaronpk** [comment]
I figured it out :joy: 

On your website you link to the instagram account "letraset" with an `e` instead of a `3`.

**Comment by voss** [comment]
Oh boy do I feel dumb. Thanks Aaron, sorry for wasting your time!

**Comment by voss** [comment]
All fixed now, and working.

**Comment by aaronpk** [comment]
I just pushed a change to the error message that shows you the instagram username, so hopefully this will be easier to spot in the future!
