### ISSUE TITLE
Add support for syndicate-to

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/OwnYourGram#6]
OwnYourGram should poll the micropub endpoint querying for syndication endpoints and present the list to the user. The user should be able to store one or more syndication targets in ownyourgram and have ownyourgram send that parameter along with each micropub endpoint.

**Comment by tantek** [comment]
For "poll the micropub endpoint querying for syndication endpoints" could that not just be check for rel=me links on the person's home page for syndication profile targets?

**Comment by aaronpk** [comment]
Interesting... currently that is described here: http://indiewebcamp.com/micropub#Discovering_Supported_Syndication_Targets

I think looking for rel=me wouldn't actually be a good idea because there may be many rel=me links that aren't syndication targets. The goal of querying the endpoint for supported syndication targets is that these are then presented to the user. Here is an example of Quill showing the list of syndications to the user in the posting interface:

![new post](https://cloud.githubusercontent.com/assets/113001/5881810/abcd4e52-a2f8-11e4-9776-ca1abd3c336a.png)

Note that Quill has no idea what these targets mean, they are just opaque strings to the micropub client.

**Comment by aaronpk** [comment]
Also would be great to add some triggers so that the user can define rules like "if the content of the instagram post matches ____ then include this syndication target"

**Comment by aaronpk** [comment]
Done in a3f7eddc399cf3c48022c96156dd7168c767d76c and bc891fa7f53f45fa22e21d5e99ebff208bd5cf74

**Comment by aaronpk** [comment]
brief writeup: https://aaronparecki.com/2016/12/21/14/100daysofindieweb
