### ISSUE TITLE
Error verifying Instagram account

### ISSUE THREAD

**Issue by cygnoir** [aaronpk/OwnYourGram#62]
I noticed that my latest Instagram photos did not publish to my Micro.blog, so I disconnected Instagram and tried setting it up again. Now I keep receiving the error message stating that I must add a link to my website in my Instagram account. I've double-checked that [my Micro.blog URL](http://cygnoir.micro.blog/) is already in the "Website" field on [my Instagram profile](https://www.instagram.com/cygnoir/).

**Comment by vishae** [comment]
I'm also facing the same issue - I've added my URL to both my [Instagram bio and Instagram website field](https://www.instagram.com/vishae/) but I'm still getting the error message saying I need to add my link to my Instagram account.

**Comment by cygnoir** [comment]
Hi, Aaron! I tried it and I'm getting this response on the site now: "Your account is currently being checked **every 24 hours**. Your account was last checked **6 days ago** and will be checked again in **just now**."

**Comment by aaronpk** [comment]
That's good! It was probably confused because of the Instagram failures. You should hopefully see some photos appear soon!

**Comment by cygnoir** [comment]
OK. I'll be patient and see what comes through. Thanks!

**Comment by vishae** [comment]
The verification went through for me, so thank you for fixing that.

I hope you don't mind me asking one more question. I'm not very tech savvy compared to others who are setting up their own blogs and to be honest I'm following a lot of the tutorials without really understanding all that's going in the back end.
After the account verification, OwnYourGram said to try sending one of my previous posts to my site to make sure it's all kosher. But it gave me this response instead:

Error!
There was an error posting the photo to your website. Please check that you're handling the expected parameters and returning the "Location" header and try again.

I'm not actually sure what that means. I've installed all the indieweb WP plugins and activated them, I'm not sure what I need to change to make this bit work...

Regards,

Serena

**Comment by matthilt** [comment]
I had the same thing happen to me yesterday. I tried again last night and everything went through OK.

If I recall I had a HTTP 500 error along with that as well.

**Comment by cygnoir** [comment]
Everything came through for me. Thanks!

**Comment by vishae** [comment]
I'm afraid I'm still getting that same error.

In the raw response, it says at the bottom, "unauthorised". How do I get it authorised?

Regards,

Serena

**Comment by aaronpk** [comment]
@vishae can you try signing out of OwnYourGram and then signing back in? It looks like it's confused about your account after the wordpress indieauth plugin upgrade.

**Comment by vishae** [comment]
I just tried logging in with a new browser and still got the same error message. Raw response:
HTTP/1.1 100 Continue

HTTP/1.1 401 Unauthorized
Server: nginx/1.12.2
Date: Sun, 22 Apr 2018 05:47:25 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Link: <https://www.serenawho.com/wp-json/indieauth/1.0/token>; rel="token_endpoint", <https://www.serenawho.com/?micropub=endpoint>; rel="micropub", <https://www.serenawho.com/wp-json/webmention/1.0/endpoint>; rel="webmention", <https://www.serenawho.com/wp-json/webmention/1.0/endpoint>; rel="http://webmention.org/"
X-Endurance-Cache-Level: 2

"Unauthorized"

Regards,

Serena

**Comment by aaronpk** [comment]
@vishae Can you try this fix? Creating the `.htaccess` file with either 

```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```

or 

```
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

https://wordpress.org/plugins/micropub/#faq-header

**Comment by vishae** [comment]
Hi @aaronpk 

When I add the first line, this is the error message I get (when attempting to send a previous post to my site - after the verification process):

> HTTP/1.1 100 Continue
> 
> HTTP/1.1 500 Internal Server Error
> Server: nginx/1.12.2
> Date: Sat, 28 Apr 2018 06:32:25 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> X-Endurance-Cache-Level: 2

That is the same error message I get if I remove that line and add the second line you suggested (I'm assuming you didn't want both lines in the .htaccess file).

**Comment by aaronpk** [comment]
Okay, thanks for giving that a try. We're working on a fix and should hopefully have an update shortly.

**Comment by vishae** [comment]
@aaronpk I'm not sure if you did anything on your end, but adding this:

> SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

to .htaccess now works for me and OwnYourGram sent it's first post to my site.

**Comment by aaronpk** [comment]
Oh that's great news! I didn't change anything with OwnYourGram, but there was an IndieAuth plugin update last week!
