### ISSUE TITLE
OwnYourGram can't find my photos

### ISSUE THREAD

**Issue by adactio** [aaronpk/OwnYourGram#63]
I'm getting this message on the `/photos` page:

> We didn't find any photos in your Instagram profile. If your account is set to "private", OwnYourGram will not be able to import your photos. If you're sure you've posted photos and your account is public and are still seeing this message, you can report an issue.

(My account isn't private: <https://www.instagram.com/adactio/> )

**Comment by aaronpk** [comment]
:sigh: Instagram must have changed something again. Such a cat and mouse game. I'll look into it, sorry for the trouble.

**Comment by adactio** [comment]
Thanks so much for doing this, Aaron—I can’t imagine how frustrating it must be to have to spring into action whenever Instagram make an API change without warning.
