### ISSUE TITLE
Nothing posted to blog from ownyourgram in over a month

### ISSUE THREAD

**Issue by davidmead** [aaronpk/OwnYourGram#64]
Last photo successfully syndicated from Instagram to my blog was [March 24th](http://davidjohnmead.com/blog/2018/03/24/19656/).

Logging in today I saw this message...

![ownyourgram_dashboard](https://user-images.githubusercontent.com/1266930/39485033-9d009384-4d45-11e8-9587-03857fecd567.png)

Going through to the photos page and clicking on each of the 20 entries I get "an error occurred" message for each one...

![import_photos_-_ownyourgram](https://user-images.githubusercontent.com/1266930/39485085-bb7aa9e4-4d45-11e8-829f-5ea9ef291a97.png)

I'm now over 30 photos behind on what's on Instagram and what's been syndicated to my blog.

I am up-to-date on all the IndieWeb WP plugins too.

Any suggestions?

**Comment by aaronpk** [comment]
It looks like OwnYourGram has been getting an `Unauthorized` response from your site. Are you able to post from any other micropub clients? 

Try logging in to Quill and creating a note and see if that gives you an error. 

Is your IndieAuth plugin set to use the local endpoint? If not, you should probably switch to that, although it will require that you log in to any Micropub clients again.

Also pinging @GWG to help debug since he might have some more ideas.

**Comment by davidmead** [comment]
I logged out of Quill and logged back in.  It gave me, what looks like, the OK for all the endpoints etc. 

<img width="783" alt="sign_in" src="https://user-images.githubusercontent.com/1266930/39499290-f3cf1a34-4d7a-11e8-9f1c-ea737d4f4603.png">

I authorized using GitHub and it too me to the posting screen.  There, when I tried to post I got this error...

<img width="731" alt="new_post" src="https://user-images.githubusercontent.com/1266930/39499384-8672a978-4d7b-11e8-8df0-9c2dbe6d8d21.png">

```
HTTP/1.1 401 Unauthorized
Date: Wed, 02 May 2018 00:01:52 GMT
Server: Apache/2.2.34
X-Powered-By: PHP/5.6.21
Link: <http://davidjohnmead.com/blog/wp-json/indieauth/1.0/token>; rel="token_endpoint", <http://davidjohnmead.com/blog/?micropub=endpoint>; rel="micropub", <http://davidjohnmead.com/blog/wp-json/webmention/1.0/endpoint>; rel="webmention", <http://davidjohnmead.com/blog/wp-json/webmention/1.0/endpoint>; rel="http://webmention.org/"
Set-Cookie: wfvt_3186044557=5ae8fff257695; expires=Wed, 02-May-2018 00:31:54 GMT; Max-Age=1800; path=/; httponly
Vary: User-Agent,Accept-Encoding
Transfer-Encoding: chunked
Content-Type: application/json

"Unauthorized"
```

I have the IndieAuth WP plugin installed and it shows active - but when I go to Users > Manage Tokens there's nothing listed, just a 'Revoke Tokens' button.

I am very confused.

**Comment by aaronpk** [comment]
Okay, sounds like there might be a bug in the IndieAuth plugin then. Pinging @dshanske. I can see that your site is set to use the external endpoints, so there might be a bug with that.

In the mean time, the token settings are in the main settings panel. If you change to the local endpoints I suspect you'll have better luck, and that's also a better long-term plan anyway. 

<img width="1048" alt="screenshot 2018-05-01 17 48 48" src="https://user-images.githubusercontent.com/113001/39500238-eb05bac4-4d67-11e8-8ce1-7616c8bd9487.png">

**Comment by davidmead** [comment]
Thanks. I'll try that tonight.

David Mead

http://twitter.com/davidmead
http://davidjohnmead.com
http://dmwebsites.com

**Comment by davidmead** [comment]
@aaronpk Going into my settings it looks like it's already set to use Local Endpoints.  Maybe that's the issue?
![image](https://user-images.githubusercontent.com/1266930/39555183-4633a112-4e45-11e8-9f08-6ea22d9e90f3.png)

Not sure what could've change to cause this issue.

**Comment by aaronpk** [comment]
Well I confirmed that OwnYourGram does in fact update the access token when you log back in, so we're back to square one here.

@davidmead what URL are you entering in OwnYourGram when you log in? I see a few different accounts for you, at various levels of functioning. 

Right now, the account OwnYourGram is using is `http://davidjohnmead.com/`, but that doesn't look like a wordpress site. It looks like you have wordpress installed at `http://davidjohnmead.com/blog/`. So if you log in to OwnYourGram with `http://davidjohnmead.com/blog/` and set that one up, then I'm guessing everything will work like expected.

**Comment by dougbeal** [comment]
I'm having the same problem with OYG and OYS at https://dougbeal.com

**Comment by davidmead** [comment]
Thanks @aaronpk. I've just gone in and updated my Instagram profile URL to http://davidjohnmead.com/blog and went through OwnYourGram again and it all seems to be working :-)

I guess I should be using http://davidjohnmead.com/blog/ on all the profiles from now on then, including Brid.gy etc.

Thanks for the fix @Ruxton. I made sure I updated all the WP Indieweb plugins before I tried this.

**Comment by aaronpk** [comment]
That's great to hear @davidmead! 

@dougbeal, OYG is getting back an HTTP 401 error from your site. We'll need to debug that separately, it's likely related to the HTTP Authorization header getting blocked by your web host.
