### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by vishae** [aaronpk/OwnYourGram#66]
Just tried logging in - I've already authorised weeks ago, and I get this error:
![2018-06-11_22-45-44](https://user-images.githubusercontent.com/6110232/41232466-cf2053dc-6dc9-11e8-83e9-56c73ae76c58.jpg)

Is this an issue on my end or on Instagram, or OwnYourGram?

**Comment by aaronpk** [comment]
Whoa weird! I will take a look.

**Comment by aaronpk** [comment]
Is this still happening?

It was an error in the microformats parser, and it looks like I've updated to a new version since this error occurred here.
