### ISSUE TITLE
send access token in both header and param

### ISSUE THREAD

**Issue by snarfed** [aaronpk/OwnYourGram#7]
...to support servers that can only handle one or the other, e.g. when behind a web server that strips the `Authorization` header.

background: http://indiewebcamp.com/irc/2015-02-14#t1423955287064 . related to aaronpk/Quill#4.

thanks in advance!

**Comment by aaronpk** [comment]
This was done in April 2015 😂  5f74782cd8c5863be65c14f9dd5978cb40f92b7c
