### ISSUE TITLE
Import Alt-Text from Instagram

### ISSUE THREAD

**Issue by RosemaryOrchard** [aaronpk/OwnYourGram#74]
As Instagram has recently added alt-text (in advanced settings on each post admittedly), it would be nice if we could have this posted on as mp-photo-alt.

**Comment by aaronpk** [comment]
Made some progress on this by first getting XRay to return the Instagram alt text for photos: https://github.com/aaronpk/XRay/issues/85

One interesting note is that Instagram will actually generate alt text for a photo if it recognizes stuff in the photo. I'm not sure whether this text should be included in the Micropub post to your website! Thoughts?

**Comment by aaronpk** [comment]
(note to me for later, this is the proposal for `mp-photo-alt` https://indieweb.org/Micropub-brainstorming#Alternative_text_for_photos_in_form-encoded)

**Comment by RosemaryOrchard** [comment]
I personally wouldn't want the auto generated text - just the alt text I provide. That said I can see people wanting it - would it be possible to provide an option? If not I'd personally go with no, it may be incorrect and it's not something the user has provided (Sknebel mentioned this in #dev).

**Comment by aaronpk** [comment]
I don't think I would mind having it, since it basically just benefits me in that my site is now able to provide some sort of default alt text even if I don't write it by hand. If you feel strongly about it I can definitely make it an option though.
