### ISSUE TITLE
Not working with Known 0.9.9-a

### ISSUE THREAD

**Issue by davidmead** [aaronpk/OwnYourGram#79]
Using the latest Known build 0.9.9-a I can log in to OwnYourGram, authorize, and see photos in it, but nothing is being sent to my blog.

I logged out, as well as revoking the existing token within Known, logged back in but still nothing.

On the 'Indieweb' tab, within Known, I can see it's connected
<img width="710" alt="screen shot 2019-01-05 at 10 05 05 am" src="https://user-images.githubusercontent.com/1266930/50725812-94131a80-10d1-11e9-90f9-135017eab546.png">

and it seems to be all okay on the OwnYourGram dashboard, even being able to detect the Twitter syndication available.

But nothing comes through and when I hit the 'post' button I get an error.
<img width="733" alt="screen shot 2019-01-05 at 9 58 56 am" src="https://user-images.githubusercontent.com/1266930/50725817-dc323d00-10d1-11e9-8234-5da52160d84b.png">

**Comment by funwhilelost** [comment]
One small gotcha: did you log in to OwnYourGram with the full `https://` and your URL?  I had issues in the past by putting in "funwhilelost.com" and signing into http okay, then failing to post because of a weird https issue.

**Comment by davidmead** [comment]
Good thing to check @funwhilelost, but yeah I was logged in using the full URL.

**Comment by aaronpk** [comment]
@davidmead can you try again? I just pushed a change that might fix this. (It still points to a problem with Known, but this should at least work around it).

**Comment by davidmead** [comment]
No. Sorry.

I logged in and tried, but the same error message in OYG.

I also revoked access to OYG in Known, logged out of OYG and logged in & authorized again, but still nothing.

**Comment by davidmead** [comment]
As I mentioned in Slack, I did get 2 photos to go through when I disabled the InstagramShim 0.1 plugin, but then  the third and fourth failed.

Must've been when you changed something else.

**Comment by absolonkent** [comment]
I'm not sure if this is still an open issue, but disabling the Known OAuth2 Server 0.9.9-a plugin seemed to resolve the issue for me.
