### ISSUE TITLE
URL signature expired on stored Instagram photo

### ISSUE THREAD

**Issue by jjeaton** [aaronpk/OwnYourGram#80]
In trying to test #69 with a video post, I seem to have run across an issue I can't fix.

There are two issues:
1. WordPress now has strict MIME type checking as of v5.0.1. This is not directly an OwnYourGram issue, but it may mean if the mime type from Instagram doesn't match the file extension, it will be blocked from upload.
2. I seem to have a photo in my OYG database that's invalid. No amount of refreshing or posting again seems to pull the correct photo from Instagram. I've attached a screenshot below:

![2019-04-09 at 9 31 AM](https://user-images.githubusercontent.com/835509/55818135-c8202200-5aaa-11e9-8891-dd86c51bfbdd.png)

[The image link](https://scontent-sjc3-1.cdninstagram.com/vp/544a75b94c5fbe0ed6cc7d0ce6343edb/5CA4F5B5/t51.2885-15/e35/54513521_372830166647991_7115392445833486011_n.jpg?_nc_ht=scontent-sjc3-1.cdninstagram.com) says "URL signature expired"

```❯ curl -I https://scontent-sjc3-1.cdninstagram.com/vp/544a75b94c5fbe0ed6cc7d0ce6343edb/5CA4F5B5/t51.2885-15/e35/54513521_372830166647991_7115392445833486011_n.jpg\?_nc_ht\=scontent-sjc3-1.cdninstagram.com
HTTP/2 403
content-type: text/plain
content-length: 21
server: proxygen-bolt
date: Tue, 09 Apr 2019 16:36:05 GMT

URL signature expired
```

is there a way to re-pull the photo URLs from instagram?

The OWG interface doesn't show me the video link, but I believe it to be invalid as well, as I don't get a valid video uploaded when testing this in production. A .mp4 file is sent, but when I try to play it, it says it's invalid. FWIW, I have a local development install of OWG running, and this particular IG post works fine there to my local WP install.

**Comment by aaronpk** [comment]
hmm this is new... looks like Instagram must have changed how they're doing media URLs. Right now OYG caches aggressively to avoid hitting IG too much, but i'll have to make a reset button for this.

**Comment by aaronpk** [comment]
With the recent change I deployed to import a single photo by its Instagram URL, that will re-fetch the data from Instagram each time and should clear this up. So you can paste this image's URL in the import field and it should update to have the new photo URL.
