### ISSUE TITLE
Error verifying instagram account

### ISSUE THREAD

**Issue by brentajones** [aaronpk/OwnYourGram#84]
The app seems to find my instagram account ok (brentajones), but says it can't find a link to my blog (https://blog.bjones.net). I've tried it with combinations of http and https in either or both spots in the instagram profile (bio/link) to no avail. Have they changed their API again or is the issue on my end?

**Comment by brseybert** [comment]
I’m having this issue as well.

**Comment by aaronpk** [comment]
I'm seeing that Instagram is returning a redirect to the login page when the server tries to fetch profile pages now. I suspect Instagram blocked my IP address, so I'll have to figure out how best to handle this.

**Comment by aaronpk** [comment]
Ok I just did a cheap workaround, let me know if it starts working again. I suspect this is just going to be a cat and mouse game though.

**Comment by brentajones** [comment]
Yes, this has resolved for me. Thank you.

**Comment by rosiel** [comment]
It seems to be happening again. Shucks, Insta!

**Comment by aaronpk** [comment]
I'm still struggling with keeping up with existing users, so unfortunately I'm disabling new user registration for now. 

If you've logged in once before (even if you haven't set up instagram), you'll still be able to log in. So you can try periodically to get it to verify your account again, but right now it's really struggling to keep up with the rate limiting.

**Comment by aaronpk** [comment]
Sorry, there's no hope for this project in its current form.  Keep an eye out for the browser extension version of this project.

**Comment by jehanalvani** [comment]
@aaronpk When you say "there's no hope for this project in its current form" above, is that in reference to the centralized "OwnYourGram" service? I have stood up my own instance of OwnYourGram in a container, but I'm running into an issue verifying my account that's an awful lot like described above; don't suspect rate-limiting since my single client isn't likely to hit rate limits.

**Comment by jehanalvani** [comment]
Ah. That's a shame. Appreciate the effort you've put in, wish Insta didn't remain such a walled garden.

**Comment by aaronpk** [comment]
Agreed. I've just resorted to posting the photo on my website first and then posting it on Instagram separately.
