### ISSUE TITLE
OwnYourGram cant find my photos

### ISSUE THREAD

**Issue by roytang** [aaronpk/OwnYourGram#85]
Hi, the when I go the photos page, the site is telling me "We didn't find any photos in your Instagram profile. If your account is set to "private", OwnYourGram will not be able to import your photos. If you're sure you've posted photos and your account is public and are still seeing this message, you can report an issue. " This was working fine yesterday. My account is public.

**Comment by cygnoir** [comment]
This is happening to me as well, and mine was working as of yesterday too.

**Comment by aaronpk** [comment]
It looks like Instagram is cracking down and blocking apps like this from making requests to their site. I "fixed" a different version of this problem yesterday, and it appears we are now playing a cat and mouse game. I don't think I'll be able to keep up, so I'm not really sure what I'm going to do. I'll keep this issue updated as things progress though.

**Comment by roytang** [comment]
FYI, https://ownyourgram.com/photos seems to be working again, but my instagram photos in the interim were not being sent to my micropub. When I click "Post" manually in this page, they were able to be posted

**Comment by aaronpk** [comment]
Yep, as long as everyone doesn't go there at the same time it stays under the rate limit. I turned off the automatic import until I can redo it in a way I can control the rate limiting.

**Comment by jeremycherfas** [comment]
Just got the same message today.

**Comment by aaronpk** [comment]
fyi, I enabled importing again with some aggressive back-off strategies, so hopefully some photos get through periodically.

**Comment by cygnoir** [comment]
I've been trying the "import a single photo" technique but can't seem to get it to work. I enter the Instagram URL, and it seems like it's about to do something, but then it doesn't.

**Comment by aaronpk** [comment]
Do you see the spinner icon? Or does it fail before then even?

**Comment by cygnoir** [comment]
I see the spinner icon for less than a second, and then it disappears.

**Comment by aaronpk** [comment]
hm yes I'm having some trouble with it too. I will spend some time tomorrow debugging this.

**Comment by aaronpk** [comment]
Keep an eye out for the browser extension version of this project.
