### ISSUE TITLE
Moved from Micro.blog subdomain to own domain

### ISSUE THREAD

**Issue by cygnoir** [aaronpk/OwnYourGram#90]
Similar to #88 I moved from a Micro.blog subdomain to my own domain, still on Micro.blog. Is it possible to manually edit my domain so that I can login and use OwnYourGram again?

Cheers!

**Comment by aaronpk** [comment]
Instagram has been aggressively blocking scraping so OwnYourGram isn't really working anymore. I have an experimental browser extension in the works that I am planning on launching but it will require manually navigating to a photo and posting it yourself. It won't be possible to do this automatically anymore sadly. I should really just shut this whole thing down at this point, it's really sad :(

**Comment by cygnoir** [comment]
I understand! Thanks for creating it -- it was glorious while it lasted :)
